### ISSUE TITLE
Draw Straight Line

### ISSUE THREAD

**Issue by sheneeb** [aFelipeSP/pdfme#15]
Hi, Thank you for the great library,
The documentation doesn't mention straight line , i need to draw a straight line as the footer just above the page number, How can i do that , exact image that i am looking for 
![image](https://user-images.githubusercontent.com/22611975/148673182-4dc82e65-0b33-4cc3-a713-adcfe1397a6c.png)

**Comment by aFelipeSP** [comment]
Hi @sheneeb, it's great you are using the library!

For this you can use a table in the footer like this: 

```python
from random import randint

from pdfme import build_pdf

char = lambda: chr(randint(97, 122))
word = lambda low=2, high=10: ''.join(char() for _ in range(randint(low, high)))
text = lambda length, low=2, high=10: ' '.join(word(low, high) for _ in range(length))

document = {
    "style": {"text_align": "j"},
    "running_sections": {
        "footer": {
            "x": "left", "y": 800, "height": "bottom",
            "style": {"text_align": "c"},
            "content": [
                {
                    "style": {"border_width": 0, "cell_margin": 0},
                    "borders": [
                        {"pos": "h0;:", "width": 0.5}
                    ],
                    "table": [[
                        {".": ["Report Date: ", {".i": "31-Dec-21"}]},
                        {".": ["Page ", {"var": "$page"}]},
                        {".": ["Internal Audited by:"]}
                    ]]
                }
            ]
        }
    },
    "sections": [
        {
            "running_sections": ["footer"],
            "content": [{".": text(1000)}]
        }
    ]
}

with open('document.pdf', 'wb') as f:
    build_pdf(document, f)
```

In the table's dict I'm including a `style` key with a `border_width` of 0 to make all of the lines in the table desappear and `cell_margin` of 0 to reduce the margin of the cells, to make the text closer to the lines.

Later in table's `borders` list key I added a dict to make the top border different to the default one I set in `border_width`. For more information on how to override the default border and fill configuration set in table's `style` got to https://pdfme.readthedocs.io/en/latest/modules/table.html#pdfme.table.PDFTable .

**Comment by sheneeb** [comment]
Thank you for your quick response , your active support is greatly appreciated.
