### ISSUE TITLE
Typographer’s apostrophe (’) in strings leads to a KeyError: '’' in fonts.py / get_text_width()

### ISSUE THREAD

**Issue by bohning** [aFelipeSP/pdfme#23]
The title pretty much says it all – I am passing a string that contains a typographer’s apostrophe to `content1.append()` and the subsequent `build_pdf(document, f)` fails with a `KeyError: '’'`.

Current workaround: replacing the (correct) typographer’s apostrophe by the typewriter’s apostrophe: `str.replace("’", "'")` before passing it to `content1.append()`.

**Comment by aFelipeSP** [comment]
sorry for the late answer. Currently this library support only the 14 standard fonts of PDF, namely Times-Roman, Helvetica, Courier, Symbol, Times-Bold, Helvetica-Bold, Courier-Bold, ZapfDingbats, Times-Italic, Helvetica-Oblique, Courier-Oblique, Times-BoldItalic, Helvetica-BoldOblique and Courier-BoldOblique. These fonts support only a set of latin characters listed in the "Document management — Portable document format — Part 1: PDF 1.7" page 653. So in theory you could use a "quoteright" charcter (with a char code of 220) to get a typographer’s apostrophe.
