### ISSUE TITLE
TypeError on BytesIO image in table

### ISSUE THREAD

**Issue by SaschaKrug** [aFelipeSP/pdfme#25]
Another issue I found with BytesIO images. it will fail with `TypeError: when image is of type io.BytesIO, image_name must be provided`, if you try to add a BytesIO image in a table.

Reason is the following part:
https://github.com/aFelipeSP/pdfme/blob/759e9d38ce073f9de1ff2202cc349a0ea72e2bd6/pdfme/table.py#L896

He is not providing the other required arguments for a BytesIO image.

An easy fix would be to use instead:
```python
            pdf_image = PDFImage(
                element['image'],
                extension=element.get('extension'),
                image_name=element.get('image_name'),
            )
```

If you like, I can provide a PR.

**Comment by aFelipeSP** [comment]
Thank you for reporting this issue, I just created a new version of the library with a fix for this.
