### ISSUE TITLE
Euro sign '€' raises a KeyError

### ISSUE THREAD

**Issue by milosta** [aFelipeSP/pdfme#27]
I saw the similar issue #23 for missing character where you referred to the PDF specification. But unlike in the #23, the specification does list the `€` sign there. Would it be possible to add it to the widths so that it would not raise a `KeyError`?

**Comment by aFelipeSP** [comment]
You can add an euro symbol like this:

```python
from pdfme import build_pdf

document = {"sections": [{"content": [{'.': chr(128)}]}]}

with open('document.pdf', 'wb') as f:
    build_pdf(document, f)
```

If you want to know the characters in a font (like Symbol or Helvetica) you can generate a PDF document like this:

```python
from pdfme import build_pdf

document = {"sections": [{"content": [{'.': ' '.join(chr(i) for i in range(256))}]}]}

with open('document.pdf', 'wb') as f:
    build_pdf(document, f)
```
That's how I found that the character for Euro is 128.
